# Generated by Django 5.2.6 on 2025-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='tamaño_ml',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
