# Generated by Django 5.2.6 on 2025-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_perfume_tamaño_ml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='tamaño_ml',
            new_name='tamano_ml',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='fecha_lanzamiento',
        ),
        migrations.AddField(
            model_name='perfume',
            name='anio_lanzamiento',
            field=models.PositiveIntegerField(blank=True, help_text='Ingrese solo el año de lanzamiento (ej: 2020)', null=True),
        ),
    ]
